apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: stock_game
  POSTGRES_USER: game_user
  POSTGRES_PASSWORD: changeme_prod_password_here
  DB_PASSWORD: changeme_prod_password_here

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: changeme_jwt_secret_here
